name: build
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install clang-tidy
        run: sudo apt install clang-tidy
      - name: Install clang-format
        run: sudo apt install clang-format
      - name: Run clang-tidy
        run: clang-tidy src/*
      - name: Run clang-format
        run: clang-format --dry-run --Werror src/*
  

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install CMake
        run: sudo apt install cmake
      - name: Run CMake
        run: cmake -S . -B ./build
      - name: Run Make
        run: make -C ./build
